const products = [
    {
      _id: '1',
      name: 'Airpods Wireless Bluetooth Headphones',
      image: '/images/airpods.jpg',
      description: 'Bluetooth technology lets you connect it with compatible devices wirelessly',
      brand: 'Apple',
      category: 'Electronics',
      price: 800.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'iPhone 11 Pro 256GB Memory',
      image: '/images/phone.jpg',
      description: 'Introducing the iPhone 11 Pro. A transformative triple-camera system.',
      brand: 'Apple',
      category: 'Electronics',
      price: 50000.99,
      countInStock: 10,
      rating: 4.7,
      numReviews: 18,
    },
    {
      _id: '3',
      name: 'Samsung Galaxy S20 128GB',
      image: '/images/galaxy.jpg',
      description: 'Experience the cutting-edge Samsung Galaxy S20 with a 120Hz display.',
      brand: 'Samsung',
      category: 'Electronics',
      price: 40000.99,
      countInStock: 5,
      rating: 4.3,
      numReviews: 22,
    },
    {
      _id: '4',
      name: 'Sony WH-1000XM4 Wireless Headphones',
      image: '/images/sony.jpg',
      description: 'Industry-leading noise cancellation and exceptional sound quality.',
      brand: 'Sony',
      category: 'Electronics',
      price: 1000.99,
      countInStock: 0,
      rating: 4.8,
      numReviews: 34,
    },
    {
      _id: '5',
      name: 'Dell XPS 13 Laptop',
      image: '/images/dell.jpg',
      description: '13.3-inch FHD laptop with InfinityEdge display, powerful performance, and sleek design.',
      brand: 'Dell',
      category: 'Electronics',
      price: 30000.99,
      countInStock: 8,
      rating: 4.6,
      numReviews: 19,
    },
    {
      _id: '6',
      name: 'Canon EOS 90D DSLR Camera',
      image: '/images/canon.jpg',
      description: 'High-quality DSLR with a 32.5 MP CMOS sensor, perfect for photography enthusiasts.',
      brand: 'Canon',
      category: 'Electronics',
      price: 40000.99,
      countInStock: 4,
      rating: 4.9,
      numReviews: 45,
    },
  ];
  
  export default products;